### ISSUE TITLE
Resolve deferred PSKs from the remote static key

### ISSUE THREAD

**Issue by ausimian** [ausimian/decibel#48]
## Motivation

Decibel currently requires every 32-byte PSK in `Decibel.new/4`. Some responder protocols learn which remote static key initiated a handshake only after processing an earlier message. For `Noise_IKpsk2_25519_ChaChaPoly_BLAKE2s`, an inbound WireGuard responder can decrypt the first message and learn the initiator's static public key before the `psk2` token in its response. It should be able to select the pairwise PSK from that identity at the point where the PSK is needed.

This is distinct from session handoff in #47: a caller may need both, but late PSK selection is useful independently.

## Proposed API

Allow an arity-one resolver in a `:psks` list, alongside existing literal 32-byte PSKs:

```elixir
session =
  Decibel.new(
    "Noise_IKpsk2_25519_ChaChaPoly_BLAKE2s",
    :rsp,
    %{
      s: local_static_keypair,
      psks: [fn remote_static_key -> lookup_pairwise_psk(remote_static_key) end],
      prologue: prologue
    }
  )
```

The exact API shape can change if another form better fits Decibel, but the resolver should receive the remote **static public key** available at the PSK step, not an application-specific identity invented by Decibel. It should run in the session owner process when that PSK token is reached, rather than during `new/4`.

## Required semantics

- Keep existing literal PSK behavior and constructor validation unchanged.
- Count resolvers as PSK entries so the PSK modifier affects earlier handshake steps exactly as it does with a literal key; only selection of the key bytes is deferred.
- Invoke each resolver when its corresponding PSK token is reached, after all preceding message processing succeeds. In the IKpsk2 responder case, the callback receives the initiator's static public key learned from the first handshake message. Do not invoke it again after that token advances successfully.
- Require a 32-byte result. A missing remote static key, failed lookup, raised exception, or invalid result must produce a documented failure. Never silently substitute an all-zero PSK.
- A resolver failure must not commit partially advanced session state or emit a handshake message. Document retry behavior and that callbacks should be fast and deterministic because they run in the session owner process.
- Document that a remote static key is protocol output, not by itself an application trust decision. Applications remain responsible for authorizing peers.
- Test IKpsk2 interoperability with the existing fixed-PSK path using different keys for different remote static identities, plus unavailable-identity, invalid-result, callback-failure, and no-partial-state cases.

## Scope

This issue does not implement the session handoff proposed in #47. It also does not make PSKs mandatory: a WireGuard peer without a configured PSK can continue to pass the protocol's all-zero 32-byte value as a literal key.

**Comment by ausimian** [comment]
Update from Wagyu: this no longer blocks per-peer PSKs there, because a two-pass read already works on 1.1.0.

For `Noise_IKpsk2_25519_ChaChaPoly_BLAKE2s`, message 1 depends only on whether a PSK is present (the psk `e` rule), not on its value; the value is first mixed in at the `psk` token at the end of message 2. So a responder can:

1. Read message 1 in a session created with a placeholder PSK, then call `remote_key/1` to learn the initiator's static key.
2. Close that session, create a fresh `:rsp` session with that peer's real PSK, and read the same message 1 again.

Tested against 1.1.0:
- Pass 1 returns the initiator's static key and the 12-byte timestamp.
- Pass 2 returns the same timestamp and writes a 48-byte message 2, which the initiator accepts.
- Transport works in both directions.
- With the wrong PSK in pass 2, the initiator rejects message 2 with `Decibel.DecryptionError`.

Pass 2 costs the `es` and `ss` DH operations a second time, but only for peers with a nonzero PSK. It also only runs after pass 1 has authenticated the timestamp, which requires the initiator's static private key, so an unauthenticated sender can't trigger it. If the zero PSK is the placeholder, peers without a PSK pay nothing extra.

This issue is still worth doing, since it removes those two DH operations, but Wagyu won't wait for it.
